## General I2X settings

##
# Internal application settings
app:
 version: 0.1a
 title: i2x
 host: http://localhost:3000/
 debug: true

##
# Cache settings
# * redis: uses Redis caching, with default values
# * internal: uses internal database and controllers
cache:
 redis: true
 host: localhost
 port: 6379
 internal: false

##
# Log settings if Sentry is used
log:
 sentry: true
 dsn: http://d767ad668a844f8587c57dcbed1a198b:a3c8e700b12a4770b0eb8578f5f8dcae@127.0.0.1:9000/1
 level: low