## General I2X settings

##
# Internal application settings
app:
 version: 0.1a
 title: i2x
 host: http://localhost:3000/

##
# Cache settings
# * redis: uses Redis caching, with default values
# * internal: uses internal database and controllers
cache:
 redis: true
 host: localhost
 port: 6379
 internal: false

##
# Log settings if Sentry is used
log:
 sentry: true
 dsn: http://12ab54380f9c45628816402439f08bb2:24783b9619974ed48bb46d1d44f0302f@127.0.0.1:9000/1
 level: low